name: milk_tracker
description: A simple app to track daily milk usage and calculate monthly cost.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/milk_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/milk_icon.png"
